sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: cxm030707
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: sky-take-out-cxm
  redis:
    host: localhost
    port: 6379
    password: cxm030707
    database: 10
  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}
